name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    environment: raise-hand.learnmer.com
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - run: npm ci
      - run: npm run deploy
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN  }}
          PARTYKIT_LOGIN: ${{ secrets.PARTYKIT_LOGIN }}
          PARTYKIT_TOKEN: ${{ secrets.PARTYKIT_TOKEN }}
